modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "myjaddon"
version = "${version}"
displayName = "JCraft Example Addon"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "assets/myjaddon/icon.png"

[[dependencies.myjaddon]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myjaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myjaddon]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.myjaddon]]
modId = "jcraft"
mandatory = true
versionRange = "[0.17.0,)"
ordering = "AFTER"
side = "BOTH"
